# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.box = "oel6base/chefdk" || "oel6base"

	# Without this set to false this box WILL NOT work as a base box
	config.ssh.insert_key = false

	config.vm.synced_folder "../../common/roles", "/opt/ansible-skeleton/common/roles"
	config.vm.synced_folder "../../applications/chef/roles", "/opt/ansible-skeleton/application/roles"

	# Stop the evil VirtualBox Guest Addition auto update
	config.vbguest.auto_update = false

	config.vm.define 'basebox' do |machine|
	
		machine.vm.provision :ansible_local do |ansible|
				ansible.config_file    = "ansible/ansible.cfg"
				ansible.playbook       = "ansible/site.yml"
				ansible.verbose        = "vv"
				ansible.install        = true
				ansible.limit          = "all"
				ansible.inventory_path = "ansible/hosts.ini"
				ansible.extra_vars = {
					vagrantfile_http_proxy: ENV['http_proxy'] || ''
				}
		end

	end

end





