---
- name: Ensure that facts from all servers have been gathered before configuring the dnsmasq
  hosts: all
  gather_facts: true

- name: Setup DNS
  hosts: all
  become: true
  roles:
    - dnsmasq-configurator