---
# see: http://www.morethanseven.net/2014/04/25/consul/
- name: Install dnsmasq
  become: true
  yum:
    name: dnsmasq
    state: present

- name: "Update the dnsmasq main config"
  become: true
  template:
    src: etc/dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify: "restart dnsmasq"

  # Note: change of resolv.conf doesn't require a restart but doing it anyway for good measure...
- name: "Install proper nameservers on consul servers, with Google DNS failover"
  become: true
  lineinfile:
    dest: /etc/resolv.conf
    regexp: "^nameserver 127.0.0.1"
    insertbefore: BOF
    line: "nameserver 127.0.0.1"
  notify: "restart dnsmasq"

- name: Enable dnsmasq at boot
  become: true
  service:
    name: dnsmasq
    enabled: yes
    state: started