---
- name: " "
  fail:
    msg: "Didn't pass in a valid _bash_test_code parameter {{_bash_test_code}}"
  when: (_bash_test_code is undefined) or (_bash_test_code is none)
  ignore_errors: true
  register: result
- name: " "
  debug:
    msg:
      "{{result}}"
  when: result | failed

- name: " "
  fail:
    msg: "Didn't pass in a valid test case name [{{_test_case_name}}]"
  when: (_test_case_name is undefined) or (_test_case_name is none)
  ignore_errors: true
  register: result
- name: " "
  debug:
    msg:
      "{{result}}"
  when: result | failed
