---
################################################################################
#               Test whether the input parameters are valid                    #
################################################################################
# using "fail" instead of "assert" because assert clutters the output with debug
- name: " "
  include_tasks: _debug_if_invalid_input_parameters.yml
  when: (_bash_test_code is undefined) or (_bash_test_code is none) or
        (_test_case_title is undefined) or (_test_case_title is none)

################################################################################
#                         Run the custom test                                  #
################################################################################
- name: "{{_test_case_title}}"
  shell:
    cmd: |
      {{_bash_test_code}}
  args:
    executable: /bin/bash
  register: result
  changed_when: false
  ignore_errors: true
  no_log: true

################################################################################
#      Print the result IFF the test failed or _should_debug_test=true         #
################################################################################
- name: " "
  include_tasks: _print_results_of_the_tests.yml
  when: ((result.rc | default(0)) != 0) or ( _should_debug_test | default(false) )