---
#- name: Ensure that kernels also update
#  replace:
#    dest: /etc/yum.conf
#    regexp: '^exclude=kernel\*'
#    replace: '#exclude=kernel*'

- name: Ensure /etc/yum.conf contains 'proxy'
  become: true
  ini_file:
    create: no
    no_extra_spaces: true
    path: /etc/yum.conf
    section: main
    state: present
    option: proxy
    value: "{{proxy_configurator_http_proxy}}"

- name: Ensure /etc/yum.conf contains 'proxy_username'
  become: true
  ini_file:
    create: no
    no_extra_spaces: true
    path: /etc/yum.conf
    section: main
    state: present
    option: proxy_username
    value: ""

- name: Ensure /etc/yum.conf contains 'proxy_password'
  become: true
  ini_file:
    create: no
    no_extra_spaces: true
    path: /etc/yum.conf
    section: main
    state: present
    option: proxy_password
    value: ""

- name: Ensure http proxy is setup in common for all users
  become: true
  template:
    force: true
    src: "etc/profile.d/proxy.sh.j2"
    dest: "/etc/profile.d/proxy.sh"
    owner: root
    group: root
    mode: 0755


